### PR TITLE
Let's make CellBinder's nib property optional.

### PR DESCRIPTION
**Pull request by dvlprliu**
In this Pull Request, I do some changes to the `CellBinder` class.
- Change `nib` property to optional
-  Add a `cellType: AnyClass?` property

So we can implement our Cell without using a Nib.

### CODE REVIEW

**Comment by ishkawa** [comment]
Great! 

Since `nib` and `cellType` have the same purpose, I think they should be the same single property. To express 3 methods to register cell to `UICollectionView`, the type of the property may look like below.

```swift
public struct CellBinder {
    enum RegistrationMethod {
        case nib(UINib)
        case `class`(AnyClass)
        case none // for storyboard
    }

    var registrationMethod: RegistrationMethod

    ...
}
```

This change eliminates expected cases such as `nib == nil && cellType == nil` and `nib != nil && cellType != nil` in compile time.

**Comment by dvlprliu** [comment]
Yeah, this is a better idea. I’ll do a new commit to make it work. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dvlprliu** [comment]
Hi, I pushed a new commit to this PR, I added a `RegistrationMethod` enum and refactor the init method of `CellBinder`.  I added two init method, a convenient one and a designated one.

While I was making the change, I got this method calls which I think a little bit verbose
```swift
CellBinder(
    cellType: RelatedVenueCell.self,
    registrationMethod: .class(RelatedVenueCell.self),
    reuseIdentifier: "id",
    configureCell: { _ in }
)
```

Since we already have the `cellType` information, So I implemented a convenient init method to make use of that to make the api clear, and it look like this:

```swift
CellBinder(
    cellType: RelatedVenueCell.self,
    reuseIdentifier: "id",
    configureCell: { _ in }
)
```

**Comment by ishkawa** [comment]
Looks good 👍 

Last one thing, I hesitate to introduce the convenience initializer. Actually, specifying the same class twice is redundant, but the convenience initializer introduces implicit promise that `registrationMethod = .class` is specified if one omit the parameter. It is not straightforward from call-site.

**Comment by dvlprliu** [comment]
Emm 🤔, it makes sense, I'll delete the convenience initializer.

**Comment by ishkawa** [comment]
:100:

Going to merge this with following small fixes:

- Redirect deprecated initializer to the new initializer, since it's not `@unavailable`.
- Use the new initializer in unit tests.

Thank you for the great work!

**Pull request merged**
